version: '3.8'

services:

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sourabh@6260
      POSTGRES_DB: irctc_db

    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"